[package]
name = "multisweeper-server"
version = "0.1.0"
edition = "2024"
default-run = "multisweeper-server"

[dependencies]
anyhow = "1.0.104"
asyncapi-rust = "0.4.0"
multisweeper-core = { version = "0.1.0", path = "../multisweeper-core" }
schemars = { version = "1.1", features = ["derive"] }
thiserror = "2.0.19"
serde = {version = "1.0.228", features=["derive"]}
serde_json = "1.0.145"
tokio = {version = "1.53.1", features=["full"]}
tokio-stream = "0.1.17"
tokio-tungstenite = "0.28.0"
tracing = "0.1.44"
tracing-forest = {version="0.3.0", features=["ansi", "chrono", "tokio"]}
tracing-futures = "0.2.5"
tracing-subscriber = {version="0.3.22", features=["env-filter"]}
futures-util = { version = "0.3.33" }
futures-macro = "0.3.33"
clap = { version = "4.6.5", features = ["derive"] }
triomphe = "0.1.16"
parking_lot = "0.12.5"
futures = "0.3.33"
rand = "0.10.2"
